version: '3'
services:
  # this container will run Cypress test
  e2e:
    image: "cypress/included:4.0.1"
    container_name: cypress
    command: "--browser chrome"
    # mount the host directory cypress and the file cypress.json as
    # volumes within the container "e2e" container
    #
    # this means that:
    #  1. anything that Cypress writes to these folders (e.g., screenshots,
    #     videos) appears also on the Docker host's filesystem
    #  2. any change that the developer applies to Cypress files on the host
    #     machine immediately takes effect within the e2e container (no docker
    #     rebuild required).
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
